---
title: "ENTSAPP Reference manual"
author: "Josep Pueyo-Ros"
format: html
toc: true
number-sections: true
---

::: {.callout-note}

This document is work in progress. Content will evolve as the tool evolves.

:::

# Knowledge base

## Technologies

## Scientific case-studies

## Commercial case-studies

## Water inputs and transformations

### Water types

```{r water_types}



```

### Conversions

# Selection of technologies


# Surface estimation {#sec-surface-estimation}

## Treatment surface

## Retention - infiltration surface

The volume that the technology can manage is calculated as follows:

$$
Q = S(\frac{I· 24}{1000} + C · D)
$$
where:

- _Q_ = Daily flow that the technology can retain or infiltrate (m^3^3/day).
- _S_ = surface of the technology (m^2^2)
- _I_ = infiltration rate of the receiving environment (mm/hour)
- _C_ = storage capacity of the technology (m^3^/m^3^)
- _D_ = depth of the technology (in m)

Note that if the infiltration is not allowed in the receiving environment, _I_ can be set to zero and then only detention is considered. The equation assumes that the technology is empty when the rain starts and that the rain lasts for 24 hours.

From the previous equation, the surface can be estimated as follows:

$$
S = \frac{Q}{0.024I + C · D}
$$
The output contains the surface needed to retain or infiltrate the volume reported and the daily volume that can be retained or infiltrated by the technology with the high interval of the surface.

When the user also provides the available area, the surface estimated is to manage all the volume reported, regardless of the available area. However, the `daily_flow` reports the maximum volume that can be retained or infiltrated by the technology using the available area. If the surface needed is lower than the available area, the daily flow always equal to the volume reported by the user. A flag named `enough_area` indicates when the available area is larger than the surface needed to manage the reported flow.

# Multicriteria decision analysis

Multicriteria decision analysis (MCDA) is a method to weight different criteria to get a final score for each technology. Each criteria is weighted between 0 and 5 regarding the importance that the criteria has in the use case.

## Criteria

### Environmental impact

It is calculated as a combination of energy use, eutrophication risks and biohazard risks, at this moment it is not calculated from rain and runoff technologies because all variables used have the same value and, therefore, the environmental impact is the same for all technologies:

$$
EI = \frac{(1 - e) + r_{NH_4} + r_{NO_2} + (1 - \frac{br}{3})}{4}
$$

Where $EI$ is environmental impact ($\in[0,1]$) being 1 the lowest impact; $e$ is energy use ($\in{0,1}$); $r_{NH_4}$ is the capacity of the technology to remove ammonia ($\in\{0,1\}$); $r_{NO_2}$ is the capacity of the technology to remove nitrates ($\in\{0,1\}$); and $br$ is the biohazard risk of the technology ($\in[0,3]$).

### Multifunctionality

Multifunctionality considers the capacity of the tehcnology to provide cobenefits and ecosystem services. It is calculated as an average of all cobenefits:

$$
M = \frac{1}{N}\sum_{i = 1}^N{\frac{cb_i}{3}}
$$

Where $M$ stands for multifunctionality ($\in[0,1]$) being 1 the highest multifunctionality; $N$ is the number of considered cobenefits; and $cb_i$ is the score for the cobenefit $i$ ($\in[0,3]$). 

### Space requirements

Space requirements is the surface needed for the technology. In case, the scenario has enough information to estimate the surface, the estimated mean surface is used. Otherwise, the ratio $m2/pe$ for each technology is used instead. The surfaces of compared technologies are normalized as follows:

$$
SR_i = \frac{s_{min}}{s_i}
$$
where $SR_i$ is the space requirements ($\in(0,1]$) for technology $i$; $s_{min}$ is the minimum surface among all compared technologies and $s_i$ is the surface of technology $i$. when the data to estimate the surface is not provided, the ratio of $m^2/pe$ is used for treatment technologies (larger ratio equals to smaller score) and $sc * d$ is used for stormwater management technologies. See @sec-surface-estimation for more details.

### Operation and manteinance

Operation and manteinance is the level of difficulty in keep the technology properly working. It is estimated as a combination of required manpower and required skills:

$$
OM = 1 - \frac{m + s}{6}
$$
Where $OM$ is the operation and manteinance score ($\in[0,1]$) being 1 the lowest operation and manteinance requirements; $m$ is the level of required manpower ($\in[0,3]$); and $s$ is the level of required skills ($\in[0,3]$).

### Cost

The cost is calculated as the total construction cost using the estimated surface. The costs for all technologies are normalized regarding the technology with the minimal cost.

$$
\hat{c}_i = \frac{c_{min}}{c_i}
$$
where $\hat{c}_i$ is the normalized construction cost ($\in(0,1]$) for technology $i$; $c_{min}$ is the minimum cost among all compared technologies and $c_i$ is the cost of technology $i$.

## Weights

Each criteria is weighted by the user according to the priorities of the specific case. Each criteria can be weighted using a 5-point Likert scale from "Not important at all" to "Very important". Then this information is used to weight the score of each criteria.

Then this weights are converted to proportions ($\Sigma{w} = 1$). Therefore, weighted all criteria as very important get the same results that weighted all of them as not important:

$$
p_{wc} = \frac{w_c}{\Sigma{w}}
$$
where $p_{wc}$ is the proportion ($\in[0,1]$) of the weight for criteria $c$; $w_c$ is the weight ($\in[0,5]$) for criteria $c$ and $\Sigma{w}$ is the sum of the weights of all criteria.
